# Generated by Django 5.2.14 on 2026-05-25 09:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Space',
            fields=[
                ('space_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=15)),
                ('keyword', models.CharField(blank=True, max_length=8)),
                ('max_capacity', models.IntegerField(validators=[django.core.validators.MaxValueValidator(12)])),
                ('duration_days', models.IntegerField(validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(365)])),
                ('is_public', models.BooleanField(default=True)),
                ('record_cycle', models.CharField(max_length=50)),
                ('record_limit', models.CharField(max_length=50)),
                ('invite_token', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField()),
            ],
        ),
    ]
