# Generated by Django 5.2.14 on 2026-05-25 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='space',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
