# Generated by Django 5.2.14 on 2026-06-01 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0002_alter_space_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='space',
            name='keyword',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
