# Generated by Django 5.2.14 on 2026-06-13 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0004_spacemember'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spacemember',
            old_name='space_id',
            new_name='space',
        ),
        migrations.RenameField(
            model_name='spacemember',
            old_name='user_id',
            new_name='user',
        ),
    ]
